### ISSUE TITLE
Update request - Can I enable caps lock key

### ISSUE THREAD

**Issue by doctordns** [PowerShell/Community-Blog#10]
Show how to ensure input from screen is in all upper case.

# Summary of the update request

- Link to the post in the old blog:
https://devblogs.microsoft.com/scripting/can-i-enable-the-caps-lock-key/

- Description of what needs to be changed:
Should talk about system.string then  needs to be updated to be in PowerShell

**Comment by Abrechnung1** [comment]
Hello Thomas,

**Your link is definitely not right here.** It belongs to onther "issue" of course ( did somebody copy & paste it :-) 

_I just stumbled over this "powershell blog" incidently from https://devblogs.microsoft.com/powershell-community/announcing-the-powershell-community-blog/ 
Well, it did sound like a great idea, as I had a lot of fun some years ago taking part in "the scripting games", learning and having fun with PS and I even wrote some blog articles for Ed and Teresa a long time ago .... ( I even met them once in Dortmund ) 

So it might be great to follow this kind of blog here, I think ... but Github is still something, I'm not good with!  :-(_ 

kind regards 
Klaus (Schulte)

**Comment by doctordns** [comment]
Good catch - a bad cut/paste from Excel. Fixed!

You raise a good point. This GitHub repo is for folks who want to get involved more directly with the content of the blog.  You can watch this work in progress, including which articles we are planning on as well as to provide a place for you to report blog post issues, to offer suggestions for old posts to bring forward, and to suggest new articles we can provide here. 

But to just consume (and possibly comment),  you can go directly to the blog itself: https://devblogs.microsoft.com/powershell-community/. The blog uses WordPress so you can provide comments which I will try to respond to as quickly as possible.  I hope the blog gets community conversations going. I see the have some spicy comments already. Feel free to pile on - just keep it classy.

I am hoping this blog can provide good skills as well as background knowledge around PowerShell (and OS) features.  I very much do want to challenge the community for input and while this blog may not run another scripting games competition, we might be able to do something.  What would it take to get YOU excited?

**Comment by KES48** [comment]
Just some things to answer: "What would it take to get YOU excited?"

The global answer: Nearly everything I don't know about PS by now but would really easy my day with PS and Co. :-)
I Stopped following PS versions with the latest Windows Powershell V5.xxxx and I can't count the number of cmdlets already available but not in my personal repertoire ... not to mention all the available modules  :-)

Well, getting help with all the pitfalls is something that would make my life brighter.
Things like Get-ChildItem does only do what I expected if I add the recurse, include, exclude and filter parameters for this or that reason make me crazy. Something like Get-Item can't  find hidden or system files is mind blowing especially if you didn't know it and something is going wrong in production ... just for a silly reason!

Just some examples from daily work, but there's a lot of truth in those little pitfalls that make my colleagues dislike PS even nowadays.
Unexpected behaviour, hard to read, difficult error handling, too may ways to do the same job, remoting and all the possible reasons that it fails .... and so on and on. Performance is something most people don't pay attention to ... but I think we all should think of it more and more. Logging, using Databases, Alerting and all this critical stuff is something in daily work which might be improved. Knowledge about building (and using) modules is still an issue here.

I don't know much about PS core ... we might not need ist because we are stuck with windows platforms  in my department, but I personally would like to get to know more about it. 

I will stop for now, but hope you can see, that daily - maybe simple - problems, questions and tips are welcome because there are always things we don't know or the we think, we already know enough ..... but ......

_Have a nice day
Klaus_

**Comment by doctordns** [comment]
Just one small thing, you can indeed find hidden or system files. Except you do not find it with `Get-Item`, but with `Get-ChildItem`, like this:
```console
PS C:\Foo> Get-ChildItem -Path .\ -Attributes Hidden        

    Directory: C:\Foo

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d--h-          28/10/2018    11:20                l
--rh-          02/10/2019    13:35            436 pwsh7.txt
---hs          02/03/2013    21:13          25088 Thumbs.db

PS C:\Foo> Get-Content -Path .\pwsh7.txt
... # contents of file
```

**Comment by doctordns** [comment]
So back to the title of this issue - rewriting this old post for PowerShell 7.

I think or #40  resolves this issue - looking forward to comments.
